import { expect, test } from '@playwright/test'

test('reset functionality flow', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByTestId('teams-page')).toBeVisible()
  await page.getByTestId('generate-fixture-button').click()
  await expect(page).toHaveURL(/\/fixtures$/)
  await page.getByTestId('start-simulation-button').click()
  await expect(page).toHaveURL(/\/simulation$/)

  await page.getByTestId('play-week-button').click()
  await page.waitForLoadState('networkidle')
  await page.getByTestId('play-week-button').click()
  await page.waitForLoadState('networkidle')
  await page.getByTestId('play-week-button').click()
  await page.waitForLoadState('networkidle')
  await expect(page.getByRole('heading', { name: 'Week 3 of 6' })).toBeVisible()

  await page.getByTestId('reset-button').click()
  await expect(page.getByTestId('confirm-dialog-confirm')).toBeVisible()
  const dialog = page.getByRole('alertdialog', { name: 'Reset Simulation' })
  await expect(dialog).toBeVisible()
  await expect(dialog.getByText('This will clear all match results, standings, and predictions. Are you sure?')).toBeVisible()
  await page.getByTestId('confirm-dialog-confirm').click()
  await page.waitForLoadState('networkidle')
  await expect(page).toHaveURL(/\/$/)
  await expect(page.getByTestId('teams-page')).toBeVisible()
  await expect(page.getByTestId('generate-fixture-button')).toBeVisible()
  await expect(page.getByTestId('team-card')).toHaveCount(4)

  await page.goto('/simulation')
  await page.waitForLoadState('networkidle')
  await expect(page).toHaveURL(/\/$/)
  await expect(page.getByTestId('teams-page')).toBeVisible()
})
